### ISSUE TITLE
Rewrite all samples using structs for activities

### ISSUE THREAD

**Issue by alexshtin** [temporalio/temporal-go-samples#20]
Activities can be implemented in a few different ways. The most robust and useful way is to implement them as structs (See https://github.com/temporalio/temporal-go-sdk/pull/4). Samples still use legacy way and implement activities as single funcs.

All samples should be rewritten with structs.

**Comment by mfateev** [comment]
I have it already done. Waiting for a server release to submit: https://github.com/mfateev/temporal-go-samples/tree/struct_activities
